version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass 123@Redis
    ports:
      - "6379:6379"
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123@Mariadb
    ports:
      - "3306:3306"
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana 
    ports:
      - "3000:3000"
    

  
